{
 "title": "main",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "April 2025 Transactions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "finance",
     "rawSql": "SELECT\n  DATE_FORMAT(txn_date, '%Y-%m-%d, %a') AS txn_day, -- needs to be expressed in varchar and not date(txn_date)\n  category,\n  merchant,\n  amount\nFROM finance.expenses\nWHERE MONTH(txn_date) = 4;\n"
    }
   ]
  },
  {
   "title": "April 2025 Spending by Category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "dataset": "finance",
     "rawSql": "SELECT\n  category AS label,\n  SUM(amount) AS value\nFROM finance.expenses\nWHERE MONTH(txn_date) = 4\nGROUP BY category;\n"
    }
   ]
  },
  {
   "title": "August 2025 Transactions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "finance",
     "rawSql": "SELECT\n  DATE_FORMAT(txn_date, '%Y-%m-%d, %a') AS txn_day, -- needs to be expressed in varchar and not date(txn_date)\n  category,\n  merchant,\n  amount\nFROM finance.expenses\nWHERE MONTH(txn_date) = 8;\n"
    }
   ]
  },
  {
   "title": "August 2025 Spending by Category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "dataset": "finance",
     "rawSql": "SELECT\n  category AS label,\n  SUM(amount) AS value\nFROM finance.expenses\nWHERE MONTH(txn_date) = 8\nGROUP BY category;\n"
    }
   ]
  },
  {
   "title": "September 2025 Transactions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "finance",
     "rawSql": "SELECT\n  DATE_FORMAT(txn_date, '%Y-%m-%d, %a') AS txn_day, -- needs to be expressed in varchar and not date(txn_date)\n  category,\n  merchant,\n  amount\nFROM finance.expenses\nWHERE MONTH(txn_date) = 9;\n"
    }
   ]
  },
  {
   "title": "September 2025 Spending by Category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "dataset": "finance",
     "rawSql": "SELECT\n  category AS label,\n  SUM(amount) AS value\nFROM finance.expenses\nWHERE MONTH(txn_date) = 9\nGROUP BY category;\n"
    }
   ]
  }
 ]
}